///******************************************************************************
///     Generated by hahaconvert at 2026/1/5 17:42:14 😄😄😄
///******************************************************************************

using System;

namespace Content.Config 
{
	[Serializable]
	public enum EUnitType 
	{
		Number
	}

	[Serializable]
	public class AttributeConfig 
	{
		/// <summary>
		/// Number，百分比
		/// Permyriad，万分比
		/// </summary>
		public EUnitType unitType;

		public string name;

		public int id;
	}
}