///******************************************************************************
///     Generated by hahaconvert at 2026/1/5 17:42:14 😄😄😄
///******************************************************************************

using System;

namespace Content.Config 
{
	[Serializable]
	public enum EModifierType 
	{
		Multiplication,
		Equals
	}

	[Serializable]
	public class BuffConfig 
	{
		public string name;

		public string desc;

		public float duration;

		public float modifierParam;

		/// <summary>
		/// Addition,
		/// Subtraction,
		/// Multiplication,
		/// Division,
		/// Equals
		/// </summary>
		public EModifierType modifierType;

		public int affectAttrId;

		public string icon;

		public int id;
	}
}