///******************************************************************************
///     Generated by hahaconvert at 2026/1/5 17:42:14 😄😄😄
///******************************************************************************

using System;

namespace Content.Config 
{
	[Serializable]
	public enum EItemType 
	{
		ConsumableItem
	}

	[Serializable]
	public enum EUseType 
	{
		AttachBuff
	}

	[Serializable]
	public class ItemConfig 
	{
		/// <summary>
		/// 根据useType不同，赋予不同的意义
		/// AttachBuff，附加的buffId
		/// 
		/// </summary>
		public string useParam;

		/// <summary>
		/// AttachBuff，附加Buff
		/// </summary>
		public EUseType useType;

		/// <summary>
		/// ConsumableItem，消耗性物品
		/// </summary>
		public EItemType itemType;

		public string assetPath;

		public string icon;

		public string desc;

		public string name;

		public int id;
	}
}