
///******************************************************
///            Generated by hahaconvert 😄😄😄
///******************************************************
namespace MMORPG.Config {
	public class JobConfig {
		public string id;
		public string name;
		public string head_pic;
		public string job_pic;
		public string prefab_name;
		public string desc;
		public string attack;
		public string defense;
		public string hit;
		public string dodge;
		public string cri;
		public string res;
		public string used_phy_attack_ids;
		public string used_skill_ids;
	}
}