
///******************************************************************************
///     Generated by hahaconvert at 9/4/2023, 11:58:12 PM 😄😄😄
///******************************************************************************

	public class JobConfig {

		/// <summary>
		/// 编号
		/// </summary>
		public int id;

		/// <summary>
		/// 职业名称
		/// </summary>
		public string name;

		/// <summary>
		/// 头像
		/// </summary>
		public string headPic;

		/// <summary>
		/// 职业半身像
		/// </summary>
		public string jobPic;

		/// <summary>
		/// 预设名称
		/// </summary>
		public string prefabName;

		/// <summary>
		/// 职业描述
		/// </summary>
		public string desc;

		/// <summary>
		/// 系数---攻击
		/// </summary>
		public int attack;

		/// <summary>
		/// 系数--防御
		/// </summary>
		public int defense;

		/// <summary>
		/// 系数--命中率
		/// </summary>
		public int hit;

		/// <summary>
		/// 系数--闪避率
		/// </summary>
		public int dodge;

		/// <summary>
		/// 系数--暴击率
		/// </summary>
		public int cri;

		/// <summary>
		/// 系数--抗性
		/// </summary>
		public int res;

		/// <summary>
		/// 使用的物理攻击Id
		/// </summary>
		public int[] usedPhyAttackIds;

		/// <summary>
		/// 使用的技能Id
		/// </summary>
		public int[] usedSkillIds;
	}