///******************************************************************************
///     Generated by hahaconvert at 2026/1/5 17:42:14 😄😄😄
///******************************************************************************

using System;

namespace Content.Config 
{
	[Serializable]
	public class MapPlacingItemConfig 
	{
		public float probability;

		public int mapItemId;

		public int id;
	}

	[Serializable]
	public class MapStateConfig 
	{
		public MapPlacingItemConfig[] PlacingItems;

		public int freezeTileCount;

		public float switchProbability;

		public string endTileRes;

		public string tileRes;

		public string startTileRes;

		public int id;
	}

	[Serializable]
	public class MapConfig 
	{
		/// <summary>
		/// 地图状态
		/// </summary>
		public MapStateConfig[] states;

		public int defaultStateId;

		public string name;

		public int id;
	}
}