///******************************************************************************
///     Generated by hahaconvert at 2026/1/5 17:42:14 😄😄😄
///******************************************************************************

using System;

namespace Content.Config 
{
	[Serializable]
	public enum EMapItemType 
	{
		Chest
	}

	[Serializable]
	public class MapItemRewardConfig 
	{
		/// <summary>
		/// 概率
		/// </summary>
		public float Probability;

		public int rewardItemId;

		public int id;
	}

	[Serializable]
	public class MapItemConfig 
	{
		public int rewardsCount;

		public MapItemRewardConfig[] rewards;

		public float useTime;

		public string assetPath;

		public string name;

		/// <summary>
		/// Chest，宝箱
		/// </summary>
		public EMapItemType mapItemType;

		public int id;
	}
}