///******************************************************************************
///     Generated by hahaconvert at 2026/1/5 17:42:14 😄😄😄
///******************************************************************************

using System;

namespace Content.Config 
{
	[Serializable]
	public class MonsterConfig 
	{
		public string assetPath;

		/// <summary>
		/// 怪物简介
		/// </summary>
		public string desc;

		/// <summary>
		/// 怪物名称
		/// </summary>
		public string name;

		public int id;
	}
}