///******************************************************************************
///     Generated by hahaconvert at 2026/1/5 17:42:14 😄😄😄
///******************************************************************************

using System;

namespace Content.Config 
{
	[Serializable]
	public class RoleAttrItemConfig 
	{
		public float value;

		public int attrId;

		public int roleId;

		public int id;
	}

	[Serializable]
	public class RoleConfig 
	{
		public RoleAttrItemConfig[] roleAttrs;

		public string assetPath;

		/// <summary>
		/// 角色简介
		/// </summary>
		public string desc;

		/// <summary>
		/// 角色名称
		/// </summary>
		public string name;

		public int id;
	}
}