///******************************************************************************
///     Generated by hahaconvert at 2026/1/5 17:42:14 😄😄😄
///******************************************************************************

using System;

namespace Content.Config 
{
	[Serializable]
	public enum ECurrencyType 
	{
		Gold
	}

	[Serializable]
	public class StoreItemConfig 
	{
		public int amount;

		/// <summary>
		/// Gold
		/// Diamond
		/// </summary>
		public ECurrencyType currencyType;

		public int itemId;
	}
}